spring.datasource.url=jdbc:postgresql://localhost:5432/addb_dev?currentSchema=ad
spring.datasource.username=postgres
spring.datasource.password=admin

eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.preferIpAddress=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=ad