# Port géré par Render automatiquement
server.port=${PORT:8761}
server.address=0.0.0.0

# Mode standalone — un seul nœud Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Hostname public Render (injecté automatiquement)
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false

# Désactive l'auto-protection (inutile sur petit déploiement)
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Évite le timeout de réplication entre pairs inexistants
eureka.server.peer-node-read-timeout-ms=1000