# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Global CI

on:
  push:
    branches: [ "dev-back" ]
  pull_request:
    branches: [ "dev-back" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: List files in vinyl-catalog-service
      run: ls -la vinyl-catalog-service

    - name: Verify pom.xml exists in vinyl-catalog-service
      run: |
        if [ ! -f vinyl-catalog-service/pom.xml ]; then
          echo "pom.xml not found in vinyl-catalog-service!"
          exit 1
        fi

    - name: Build vinyl-catalog-service with Maven
      run: |
        cd vinyl-catalog-service
        mvn -B package --file pom.xml

    - name: List files in vinyl-user-service
      run: ls -la vinyl-user-service

    - name: Verify pom.xml exists in vinyl-user-service
      run: |
        if [ ! -f vinyl-user-service/pom.xml ]; then
          echo "pom.xml not found in vinyl-user-service!"
          exit 1
        fi

    - name: Build vinyl-user-service with Maven
      run: |
        cd vinyl-user-service
        mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
